
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: demodb
  datasource:
    url: jdbc:sqlserver://localhost
    password: MittPassord123!
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver